include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-external-service/backup-files.yml'

stages:
  - deploy
  - deploy-external-service

variables:
  PROJECT_PARENT_NAME: gis

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
  environment:
    url: https://${DD_GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}

.deploy-external-service:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    DD_BACKUP_VOL_NAME: geoserver-data-vol
    DD_PATHS_TO_EXCLUDE: cluster logs temp tmp
    DD_PUSHGATEWAY_LABEL: files-backup-redmic-geoserver
