include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/docker-deploy.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: gis
    STATUS_CHECK_DELAY: 360
