version: '3.5'

services:
  geoserver:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ROLE=master
      - BROKER_SERVICE_NAME=activemq
      - ACTIVEMQ_PORT
      - JAVA_OPTS=-Xmx512m -Xss512m
    networks:
      - gis-net
      - postgres-net
    volumes:
      - geoserver-vol:/var/geoserver/data
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${GEOSERVER_PORT}/geoserver
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  gis-net:
    external: true
