x-geoserver-root: &geoserver-root
  image: ${IMAGE_NAME:-kartoza/geoserver}:${IMAGE_TAG:-latest}
  networks:
    geoserver-net:
    postgres-gwc-net:
    postgres-net:
    traefik-net:
  volumes:
    - data-vol:${GEOSERVER_DATA_DIR}
    - fonts-vol:${FONTS_DIR}
    - footprints-vol:${FOOTPRINTS_DATA_DIR}
    - cache-vol:${GEOWEBCACHE_CACHE_DIR}
  healthcheck:
    test: >
      curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null
      -u '${GEOSERVER_ADMIN_USER}:${GEOSERVER_ADMIN_PASSWORD}'
      http://localhost:${GEOSERVER_PORT}${GEOSERVER_HEALTH_PATH}
    interval: ${HEALTHCHECK_INTERVAL:-30s}
    timeout: ${HEALTHCHECK_TIMEOUT:-15s}
    retries: ${HEALTHCHECK_RETRIES:-5}
    start_period: ${HEALTHCHECK_START_PERIOD:-5m}

x-geoserver-environment: &geoserver-environment
  GEOSERVER_DATA_DIR:
  GEOWEBCACHE_CACHE_DIR:
  FONTS_DIR:
  FOOTPRINTS_DATA_DIR:
  EXTRA_CONFIG_DIR:
  GEOSERVER_LOG_LOCATION: 'logs/{{.Service.Name}}-{{.Task.Slot}}.log'
  HTTP_PORT: '${GEOSERVER_PORT}'
  HTTP_SCHEME:
  HTTP_PROXY_NAME: '${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}'
  GEOSERVER_ADMIN_USER:
  GEOSERVER_ADMIN_PASSWORD:
  STABLE_EXTENSIONS:
  COMMUNITY_EXTENSIONS:
  CLUSTERING:
  RANDOMSTRING: '{{.Service.Name}}-{{.Task.Slot}}'
  INSTANCE_STRING: '{{.Service.Name}}-{{.Task.Slot}}'
  CLUSTER_DURABILITY:
  CLUSTER_CONNECTION_RETRY_COUNT:
  CLUSTER_CONNECTION_MAX_WAIT:
  TOMCAT_EXTRAS:
  ROOT_WEBAPP_REDIRECT:
  GEOSERVER_NODE_OPTS: 'id:{{.Service.Name}}-{{.Task.Slot}};background:${GEOSERVER_LABEL_BACKGROUND};color:${GEOSERVER_LABEL_COLOR}'
  CSRF_WHITELIST: '${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}'
  DB_BACKEND: postgres
  HOST: ${POSTGRES_HOST}
  POSTGRES_PORT:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASS:
  DISK_QUOTA_SIZE:
  GEOSERVER_LOG_LEVEL:
  DISABLE_CORS:
  EXISTING_DATA_DIR:
  CHOWN_DATA_DIR:
  ADDITIONAL_JAVA_STARTUP_OPTIONS:

x-geoserver-deploy: &geoserver-deploy
  mode: replicated
  restart_policy:
    delay: ${RESTART_DELAY:-5s}
  update_config:
    delay: ${UPDATE_DELAY:-5m}

x-geoserver-traefik-common-service-labels: &geoserver-traefik-common-service-labels
  traefik.enable: ${TRAEFIK_ENABLE:-true}

  traefik.http.routers.geoserver.entrypoints: ${TRAEFIK_ENTRYPOINT}
  traefik.http.routers.geoserver.rule: Host(`${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
  traefik.http.routers.geoserver.service: geoserver
  traefik.http.services.geoserver.loadbalancer.server.port: ${GEOSERVER_PORT}

  traefik.http.services.geoserver.loadbalancer.sticky.cookie: ${TRAEFIK_STICKY_COOKIE:-true}
  traefik.http.services.geoserver.loadbalancer.sticky.cookie.name: ${TRAEFIK_STICKY_COOKIE_NAME:-traefik-geoserver}
  traefik.http.services.geoserver.loadbalancer.sticky.cookie.httponly: ${TRAEFIK_STICKY_COOKIE_HTTPONLY:-true}
  traefik.http.services.geoserver.loadbalancer.sticky.cookie.secure: ${TRAEFIK_STICKY_COOKIE_SECURE:-true}
  traefik.http.services.geoserver.loadbalancer.sticky.cookie.samesite: ${TRAEFIK_STICKY_COOKIE_SAMESITE:-lax}

  traefik.http.services.geoserver.loadbalancer.healthcheck.path: ${GEOSERVER_HEALTH_PATH}
  traefik.http.services.geoserver.loadbalancer.healthcheck.headers.authorization: ${TRAEFIK_HEALTH_AUTH}

services:
  geoserver-master:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'true'
      TOGGLE_SLAVE: 'false'
      DISABLE_WEB_INTERFACE: 'false'
      EMBEDDED_BROKER: enabled
      BROKER_URL: 'tcp://0.0.0.0:${BROKER_PORT}'
      READONLY: disabled
    deploy:
      << : *geoserver-deploy
      replicas: 1
      labels:
        << : *geoserver-traefik-common-service-labels
        traefik.http.routers.geoserver-admin.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.geoserver-admin.rule: Host(`${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}`) && (PathPrefix(`/geoserver/web`) || PathPrefix(`/geoserver/rest`) || PathPrefix(`/geoserver/j_spring_security`) || PathPrefix(`/geoserver/gwc/rest`))
        traefik.http.routers.geoserver-admin.service: geoserver-master
        traefik.http.services.geoserver-master.loadbalancer.server.port: ${GEOSERVER_PORT}

  geoserver-node:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'false'
      TOGGLE_SLAVE: 'true'
      DISABLE_WEB_INTERFACE: 'true'
      EMBEDDED_BROKER: disabled
      BROKER_URL: 'tcp://geoserver-master:${BROKER_PORT}'
      READONLY: enabled
      GEOSERVER_XSTREAM_WHITELIST:
    deploy:
      << : *geoserver-deploy
      replicas: ${NODE_REPLICAS:-1}
      placement:
        max_replicas_per_node: 1
      labels:
        << : *geoserver-traefik-common-service-labels

networks:
  geoserver-net:
    name: ${GEOSERVER_NET_NAME:-geoserver-net}
    driver: ${GEOSERVER_NET_DRIVER:-overlay}
    attachable: ${GEOSERVER_NET_ATTACHABLE:-true}

  postgres-gwc-net:
    name: ${POSTGRES_GWC_NET_NAME:-postgres-gwc-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
