services:
  geoserver-master:
    environment:
      INITIAL_MEMORY: ${DEV_MASTER_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_MASTER_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${MASTER_RESOURCES_LIMITS_CPUS}'
          memory: ${DEV_MASTER_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${MASTER_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${DEV_MASTER_RESOURCES_RESERVATIONS_MEMORY}

  geoserver-node:
    environment:
      INITIAL_MEMORY: ${DEV_NODE_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_NODE_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${NODE_RESOURCES_LIMITS_CPUS}'
          memory: ${DEV_NODE_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${NODE_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${DEV_NODE_RESOURCES_RESERVATIONS_MEMORY}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${DATA_VOL_DEVICE:-/geoserver-data-vol/}

  cache-vol:
    name: ${CACHE_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${CACHE_VOL_DEVICE:-/geoserver-cache-vol/}

  fonts-vol:
    name: ${FONTS_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${FONTS_VOL_DEVICE:-/geoserver-fonts-vol/}

  footprints-vol:
    name: ${FOOTPRINTS_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${FOOTPRINTS_VOL_DEVICE:-/geoserver-footprints-vol/}
