services:
  geoserver-master:
    environment:
      INITIAL_MEMORY: ${PRO_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${PRO_MAXIMUM_MEMORY}
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '${PRO_RESOURCES_LIMITS_CPUS}'
          memory: ${PRO_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${PRO_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${PRO_RESOURCES_RESERVATIONS_MEMORY}

  geoserver-node:
    environment:
      INITIAL_MEMORY: ${PRO_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${PRO_MAXIMUM_MEMORY}
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '${PRO_RESOURCES_LIMITS_CPUS}'
          memory: ${PRO_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${PRO_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${PRO_RESOURCES_RESERVATIONS_MEMORY}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
      perfmode: maxio

  cache-vol:
    name: ${CACHE_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
      perfmode: maxio

  fonts-vol:
    name: ${FONTS_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared

  footprints-vol:
    name: ${FOOTPRINTS_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
