services:
  geoserver-master:
    environment:
      INITIAL_MEMORY: ${DEV_MASTER_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_MASTER_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${GEOSERVER_MASTER_RESOURCES_LIMITS_CPUS}'
          memory: ${DEV_GEOSERVER_MASTER_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${GEOSERVER_MASTER_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${DEV_GEOSERVER_MASTER_RESOURCES_RESERVATIONS_MEMORY}

  geoserver-node:
    environment:
      INITIAL_MEMORY: ${DEV_NODE_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_NODE_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${GEOSERVER_NODE_RESOURCES_LIMITS_CPUS}'
          memory: ${DEV_GEOSERVER_NODE_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${GEOSERVER_NODE_RESOURCES_RESERVATIONS_CPUS}'
          memory: ${DEV_GEOSERVER_NODE_RESOURCES_RESERVATIONS_MEMORY}

volumes:
  geoserver-data-vol:
    name: ${GEOSERVER_DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${GEOSERVER_DATA_VOL_DEVICE:-:/geoserver-data-vol/}

  cache-vol:
    name: ${CACHE_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CACHE_VOL_DEVICE:-:/geoserver-cache-vol/}

  fonts-vol:
    name: ${FONTS_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${FONTS_VOL_DEVICE:-:/geoserver-fonts-vol/}

  footprints-vol:
    name: ${FOOTPRINTS_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${FOOTPRINTS_VOL_DEVICE:-:/geoserver-footprints-vol/}

  postgres-data-vol:
    name: ${POSTGRES_DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${POSTGRES_DATA_VOL_DEVICE:-:/postgres-gwc-data-vol/}

  wal-vol:
    name: ${WAL_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${WAL_VOL_DEVICE:-:/postgres-gwc-wal-vol/}
