version: '3.5'

services:
  geoserver-slave:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  geoserver-vol:
    name: geoserver-vol
