version: '3.5'

services:
  geoserver-slave:
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  geoserver-vol:
    name: geoserver-maxio-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
      perfmode: maxio
