version: '3.8'

x-geoserver-root: &geoserver-root
  image: ${IMAGE_NAME:-kartoza/geoserver}:${IMAGE_TAG:-latest}

x-geoserver-environment: &geoserver-environment
  GEOWEBCACHE_CACHE_DIR:
  HTTP_PORT: '${GEOSERVER_PORT}'
  STABLE_EXTENSIONS:
  COMMUNITY_EXTENSIONS:
  CLUSTERING:
  EXISTING_DATA_DIR: 'true'
  RANDOMSTRING: '{{.Service.Name}}-{{.Task.Slot}}'
  INSTANCE_STRING: 'instance-{{.Service.Name}}-{{.Task.Slot}}'
  CLUSTER_DURABILITY:
  TOMCAT_EXTRAS:

x-geoserver-volumes: &geoserver-volumes
  - data-vol:/opt/geoserver/data_dir
  - fonts-vol:/opt/fonts
  - letsencrypt-vol:/etc/letsencrypt
  - footprints-vol:/opt/footprints_dir
  - old-cache-vol:/opt/geoserver/data_dir/gwc
  - cache-vol:${GEOWEBCACHE_CACHE_DIR}

x-geoserver-networks: &geoserver-networks
  gis-net:
  postgres-net:
  traefik-net:

services:
  geoserver-master:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'true'
      TOGGLE_SLAVE: 'false'
      WEB_INTERFACE: 'false'
      EMBEDDED_BROKER: enabled
      BROKER_URL: 'tcp://0.0.0.0:${BROKER_PORT}'
      READONLY: disabled
      INITIAL_MEMORY: ${MASTER_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${MASTER_MAXIMUM_MEMORY}
    volumes: *geoserver-volumes
    networks: *geoserver-networks
    healthcheck:
      test: curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: ${GEOSERVER_MASTER_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${GEOSERVER_MASTER_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${GEOSERVER_MASTER_HEALTHCHECK_RETRIES:-3}
      start_period: ${GEOSERVER_MASTER_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.web.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/web'
        traefik.login.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/j_spring_security_check'
        traefik.backend: geoserver-master
        traefik.port: '${GEOSERVER_PORT}'
      restart_policy:
        delay: ${GEOSERVER_MASTER_RESTART_DELAY:-10s}
      update_config:
        delay: ${GEOSERVER_MASTER_UPDATE_DELAY:-3m}
      resources:
        limits:
          cpus: '${GEOSERVER_MASTER_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${MASTER_MAXIMUM_MEMORY}
        reservations:
          cpus: '${GEOSERVER_MASTER_RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${MASTER_INITIAL_MEMORY}

  geoserver-node:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'false'
      TOGGLE_SLAVE: 'true'
      WEB_INTERFACE: 'true'
      EMBEDDED_BROKER: disabled
      BROKER_URL: 'tcp://geoserver-master:${BROKER_PORT}'
      READONLY: enabled
    volumes: *geoserver-volumes
    networks: *geoserver-networks
    healthcheck:
      test:  curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: ${GEOSERVER_SLAVE_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${GEOSERVER_SLAVE_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${GEOSERVER_SLAVE_HEALTHCHECK_RETRIES:-3}
      start_period: ${GEOSERVER_SLAVE_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      placement:
        max_replicas_per_node: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.backend: geoserver-node
        traefik.port: '${GEOSERVER_PORT}'
      restart_policy:
        delay: ${GEOSERVER_SLAVE_RESTART_DELAY:-10s}
      update_config:
        delay: ${GEOSERVER_SLAVE_UPDATE_DELAY:-3m}

volumes:
  letsencrypt-vol:
    name: ${LETSENCRYPT_VOL_NAME:-geoserver-letsencrypt-vol}

  old-cache-vol:
    name: ${OLD_CACHE_VOL_NAME:-geoserver-old-cache-vol}

networks:
  gis-net:
    name: ${GIS_NET_NAME:-gis-net}
    driver: ${GIS_NET_DRIVER:-overlay}
    attachable: true

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
