version: '3.8'

x-geoserver-root: &geoserver-root
  image: ${GEOSERVER_IMAGE_NAME:-kartoza/geoserver}:${GEOSERVER_IMAGE_TAG:-latest}

x-geoserver-environment: &geoserver-environment
  GEOWEBCACHE_CACHE_DIR:
  HTTP_PORT: '${GEOSERVER_PORT}'
  STABLE_EXTENSIONS:
  COMMUNITY_EXTENSIONS:
  CLUSTERING:
  EXISTING_DATA_DIR: 'true'
  RANDOMSTRING: '{{.Service.Name}}-{{.Task.Slot}}'
  INSTANCE_STRING: 'instance-{{.Service.Name}}-{{.Task.Slot}}'
  CLUSTER_DURABILITY:
  TOMCAT_EXTRAS:

x-geoserver-volumes: &geoserver-volumes
  - geoserver-data-vol:/opt/geoserver/data_dir
  - fonts-vol:/opt/fonts
  - letsencrypt-vol:/etc/letsencrypt
  - footprints-vol:/opt/footprints_dir
  - old-cache-vol:/opt/geoserver/data_dir/gwc
  - cache-vol:${GEOWEBCACHE_CACHE_DIR}

x-geoserver-networks: &geoserver-networks
  gis-net:
  postgres-net:
  traefik-net:

services:
  geoserver-master:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'true'
      TOGGLE_SLAVE: 'false'
      WEB_INTERFACE: 'false'
      EMBEDDED_BROKER: enabled
      BROKER_URL: 'tcp://0.0.0.0:${BROKER_PORT}'
      READONLY: disabled
    volumes: *geoserver-volumes
    networks: *geoserver-networks
    healthcheck:
      test: curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: ${GEOSERVER_MASTER_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${GEOSERVER_MASTER_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${GEOSERVER_MASTER_HEALTHCHECK_RETRIES:-3}
      start_period: ${GEOSERVER_MASTER_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.web.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/web'
        traefik.login.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/j_spring_security'
        traefik.gwc.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/gwc'
        traefik.backend: geoserver-master
        traefik.port: '${GEOSERVER_PORT}'
      restart_policy:
        delay: ${GEOSERVER_MASTER_RESTART_DELAY:-10s}
      update_config:
        delay: ${GEOSERVER_MASTER_UPDATE_DELAY:-3m}

  geoserver-node:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'false'
      TOGGLE_SLAVE: 'true'
      WEB_INTERFACE: 'true'
      EMBEDDED_BROKER: disabled
      BROKER_URL: 'tcp://geoserver-master:${BROKER_PORT}'
      READONLY: enabled
    volumes: *geoserver-volumes
    networks: *geoserver-networks
    healthcheck:
      test:  curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: ${GEOSERVER_NODE_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${GEOSERVER_NODE_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${GEOSERVER_NODE_HEALTHCHECK_RETRIES:-3}
      start_period: ${GEOSERVER_NODE_HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      placement:
        max_replicas_per_node: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.backend: geoserver-node
        traefik.port: '${GEOSERVER_PORT}'
      restart_policy:
        delay: ${GEOSERVER_NODE_RESTART_DELAY:-10s}
      update_config:
        delay: ${GEOSERVER_NODE_UPDATE_DELAY:-3m}

  postgres-gwc:
    image: ${POSTGRES_IMAGE_NAME:-postgres}:${POSTGRES_IMAGE_TAG:-alpine}
    command: >
      -c work_mem=${POSTGRES_GWC_WORK_MEM:-16MB}
      -c max_wal_size=${POSTGRES_GWC_MAX_WAL_SIZE:-256MB}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      gis-net:
    volumes:
      - postgres-data-vol:${PGDATA}
      - wal-vol:${POSTGRES_INITDB_WALDIR}
    deploy:
      mode: replicated
      replicas: ${POSTGRES_GWC_REPLICAS:-1}
      restart_policy:
        delay: ${POSTGRES_GWC_RESTART_DELAY:-1s}
      update_config:
        delay: ${POSTGRES_GWC_UPDATE_DELAY:-30s}
      resources:
        limits:
          cpus: '${POSTGRES_GWC_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${POSTGRES_GWC_RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${POSTGRES_GWC_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${POSTGRES_GWC_RESOURCES_RESERVATIONS_MEMORY:-32M}

volumes:
  letsencrypt-vol:
    name: ${LETSENCRYPT_VOL_NAME:-geoserver-letsencrypt-vol}

  old-cache-vol:
    name: ${OLD_CACHE_VOL_NAME:-geoserver-old-cache-vol}

networks:
  gis-net:
    name: ${GIS_NET_NAME:-gis-net}
    driver: ${GIS_NET_DRIVER:-overlay}
    attachable: ${GIS_NET_ATTACHABLE:-true}

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
