version: '3.9'

x-geoserver-root: &geoserver-root
  image: ${GEOSERVER_IMAGE_NAME:-kartoza/geoserver}:${GEOSERVER_IMAGE_TAG:-latest}
  networks:
    gis-net:
    postgres-net:
    traefik-net:
  volumes:
    - geoserver-data-vol:${GEOSERVER_DATA_DIR}
    - fonts-vol:${FONTS_DIR}
    - footprints-vol:${FOOTPRINTS_DATA_DIR}
    - cache-vol:${GEOWEBCACHE_CACHE_DIR}
  configs:
    - source: cluster-properties-config
      target: ${EXTRA_CONFIG_DIR}/cluster.properties
  healthcheck:
    test: curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
    interval: ${GEOSERVER_HEALTHCHECK_INTERVAL:-1m}
    timeout: ${GEOSERVER_HEALTHCHECK_TIMEOUT:-30s}
    retries: ${GEOSERVER_HEALTHCHECK_RETRIES:-5}
    start_period: ${GEOSERVER_HEALTHCHECK_START_PERIOD:-3m}

x-geoserver-environment: &geoserver-environment
  GEOSERVER_DATA_DIR:
  GEOWEBCACHE_CACHE_DIR:
  FONTS_DIR:
  FOOTPRINTS_DATA_DIR:
  EXTRA_CONFIG_DIR:
  GEOSERVER_LOG_LOCATION: 'logs/{{.Service.Name}}-{{.Task.Slot}}.log'
  HTTP_PORT: '${GEOSERVER_PORT}'
  HTTP_SCHEME:
  HTTP_PROXY_NAME: '${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}'
  GEOSERVER_ADMIN_USER:
  GEOSERVER_ADMIN_PASSWORD:
  STABLE_EXTENSIONS:
  COMMUNITY_EXTENSIONS:
  CLUSTERING:
  RANDOMSTRING: '{{.Service.Name}}-{{.Task.Slot}}'
  INSTANCE_STRING: '{{.Service.Name}}-{{.Task.Slot}}'
  CLUSTER_DURABILITY:
  TOMCAT_EXTRAS:
  GEOSERVER_NODE_OPTS: 'id:{{.Service.Name}}-{{.Task.Slot}};background:${GEOSERVER_LABEL_BACKGROUND};color:${GEOSERVER_LABEL_COLOR}'
  CATALINA_OPTS: '-DHTTP_PROXY_NAME=$${HTTP_PROXY_NAME}'
  GEOSERVER_CSRF_WHITELIST: '${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}'
  DB_BACKEND: postgres
  HOST: postgres-gwc
  POSTGRES_PORT: 5432
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASS: '${POSTGRES_PASSWORD}'
  DISK_QUOTA_SIZE:
  GEOSERVER_LOG_LEVEL:

x-geoserver-deploy: &geoserver-deploy
  mode: replicated
  restart_policy:
    delay: ${GEOSERVER_RESTART_DELAY:-10s}
  update_config:
    delay: ${GEOSERVER_UPDATE_DELAY:-3m}

services:
  geoserver-master:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'true'
      TOGGLE_SLAVE: 'false'
      WEB_INTERFACE: 'false'
      EMBEDDED_BROKER: enabled
      BROKER_URL: 'tcp://0.0.0.0:${BROKER_PORT}'
      READONLY: disabled
    deploy:
      << : *geoserver-deploy
      replicas: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.web.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/web'
        traefik.rest.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/rest'
        traefik.login.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/j_spring_security'
        traefik.gwc.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/gwc/rest'
        traefik.backend: geoserver-master
        traefik.port: '${GEOSERVER_PORT}'

  geoserver-node:
    << : *geoserver-root
    environment:
      << : *geoserver-environment
      TOGGLE_MASTER: 'false'
      TOGGLE_SLAVE: 'true'
      DISABLE_WEB_INTERFACE: 'true'
      EMBEDDED_BROKER: disabled
      BROKER_URL: 'tcp://geoserver-master:${BROKER_PORT}'
      READONLY: enabled
    deploy:
      << : *geoserver-deploy
      replicas: ${GEOSERVER_NODE_REPLICAS:-1}
      placement:
        max_replicas_per_node: 1
      labels:
        traefik.default.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver/'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.backend: geoserver-node
        traefik.backend.loadbalancer.stickiness: 'true'
        traefik.backend.loadbalancer.stickiness.cookieName: traefik-geoserver-node
        traefik.backend.loadbalancer.method: drr
        traefik.port: '${GEOSERVER_PORT}'

  postgres-gwc:
    image: ${POSTGRES_IMAGE_NAME:-postgres}:${POSTGRES_IMAGE_TAG:-alpine}
    command: >
      -c work_mem=${POSTGRES_GWC_WORK_MEM:-16MB}
      -c max_wal_size=${POSTGRES_GWC_MAX_WAL_SIZE:-256MB}
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA:
      POSTGRES_INITDB_WALDIR:
    networks:
      gis-net:
    volumes:
      - postgres-data-vol:${PGDATA}
      - wal-vol:${POSTGRES_INITDB_WALDIR}
    deploy:
      mode: replicated
      replicas: ${POSTGRES_GWC_REPLICAS:-1}
      restart_policy:
        delay: ${POSTGRES_GWC_RESTART_DELAY:-1s}
      update_config:
        delay: ${POSTGRES_GWC_UPDATE_DELAY:-30s}
      resources:
        limits:
          cpus: '${POSTGRES_GWC_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${POSTGRES_GWC_RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${POSTGRES_GWC_RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${POSTGRES_GWC_RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  gis-net:
    name: ${GIS_NET_NAME:-gis-net}
    driver: ${GIS_NET_DRIVER:-overlay}
    attachable: ${GIS_NET_ATTACHABLE:-true}

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  cluster-properties-config:
    name: ${CLUSTER_PROPERTIES_CONFIG_NAME:-geoserver-cluster-properties-config}
    file: ./config/cluster.properties
