version: '3.5'

services:
  geoserver-slave:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - JAVA_OPTS=-DGEOSERVER_CONSOLE_DISABLED=true -DPROXY_BASE_URL=https://${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}/geoserver
    networks:
      - gis-net
      - postgres-net
      - traefik-net
    volumes:
      - geoserver-vol:/var/geoserver/data
    healthcheck:
      test:  curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      labels:
        traefik.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.frontend.headers.customResponseHeaders: 'Access-Control-Allow-Origin:*'
        traefik.backend: geoserver-slave
        traefik.port: '${GEOSERVER_PORT}'
      restart_policy:
        delay: 1m
        window: 3m

networks:
  gis-net:
    name: ${GIS_NET_NAME:-gis-net}
    attachable: true

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true