version: '3.9'

services:
  geoserver-master:
    environment:
      INITIAL_MEMORY: ${DEV_MASTER_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_MASTER_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${GEOSERVER_MASTER_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${DEV_GEOSERVER_MASTER_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${GEOSERVER_MASTER_RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${DEV_GEOSERVER_MASTER_RESOURCES_RESERVATIONS_MEMORY}

  geoserver-node:
    environment:
      INITIAL_MEMORY: ${DEV_NODE_INITIAL_MEMORY}
      MAXIMUM_MEMORY: ${DEV_NODE_MAXIMUM_MEMORY}
    deploy:
      resources:
        limits:
          cpus: '${GEOSERVER_NODE_RESOURCES_LIMITS_CPUS:-1}'
          memory: ${DEV_GEOSERVER_NODE_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: '${GEOSERVER_NODE_RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${DEV_GEOSERVER_NODE_RESOURCES_RESERVATIONS_MEMORY}

volumes:
  geoserver-data-vol:
    name: ${GEOSERVER_DATA_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}

  cache-vol:
    name: ${CACHE_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}

  fonts-vol:
    name: ${FONTS_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}

  footprints-vol:
    name: ${FOOTPRINTS_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}

  postgres-data-vol:
    name: ${POSTGRES_DATA_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}

  wal-vol:
    name: ${WAL_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
