version: '3.5'

services:
  geoserver-slave:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - JAVA_OPTS=-DGEOSERVER_CONSOLE_DISABLED=true -DPROXY_BASE_URL=https://${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}/geoserver
    networks:
      - gis-net
      - postgres-net
      - traefik-net
    volumes:
      - geoserver-vol:/var/geoserver/data
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${GEOSERVER_PORT}/geoserver
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 4m

networks:
  gis-net:
    external: true

  postgres-net:
    external: true

  traefik-net:
    external: true
