version: '3.5'

services:
  geoserver-master:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - GEOSERVER_PORT
      - GEOSERVER_USER
      - GEOSERVER_PASS
      - SLAVE_SERVICE_NAME
      - SLAVES_MANAGEMENT_DELAY
      - SLAVES_MANAGEMENT_INTERVAL
      - SLAVE_MANAGEMENT_TIMEOUT
      - ROLE=master
      - SWARM_MODE=true
      - JAVA_OPTS=-DPROXY_BASE_URL=https://${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}/geoserver
    networks:
      - gis-net
      - postgres-net
      - traefik-net
    volumes:
      - geoserver-vol:/var/geoserver/data
    healthcheck:
      test: curl --fail --silent http://localhost:${GEOSERVER_PORT}/geoserver
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.admin.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};PathPrefix:/geoserver'
        traefik.root.frontend.rule: 'Host:${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME};Path:/;AddPrefix:/geoserver'
        traefik.backend: geoserver-master
        traefik.port: '${GEOSERVER_PORT}'
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M

networks:
  gis-net:
    name: ${GIS_NET_NAME:-gis-net}
    attachable: true

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true
