version: '3.5'

services:
  geoserver:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - GEOSERVER_PORT
      - HAZELCAST_PORT
      - CLUSTER_NAME
      - CLUSTER_PASSWORD
      - SYNC_MODE
      - SYNC_DELAY
      - SESSION_STICKY
      - CLUSTER_DISCOVERY_URL
      - JAVA_OPTS=-DPROXY_BASE_URL=https://${GEOSERVER_SUBDOMAIN}.${PUBLIC_HOSTNAME}/geoserver
    networks:
      - gis-net
      - postgres-net
      - traefik-net
    volumes:
      - geoserver-vol:/var/geoserver/data
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${GEOSERVER_PORT}/geoserver
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 4m

networks:
  gis-net:
    external: true

  postgres-net:
    external: true

  traefik-net:
    external: true
